### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Maratyszcza** [zwegner/x86-info-term#2]
This project is very interesting, but unfortunately doesn't specify a license.

**Comment by zwegner** [comment]
Thanks for reminding me! I hadn't thought too much about it, since this is mostly an end-user tool and I didn't think there was much of a chance for forks or integration with other projects.

I tend to prefer (A)GPL for bigger projects, and MIT (or similar) for small libraries. I might go for GPL here, but don't feel very strongly in this case. Is there some code here you'd like to integrate with another project?

(BTW, I recently ran across PeachPy, it's very nice!)

**Comment by Maratyszcza** [comment]
Big companies have rules, and one of the rules is that we can't use projects without a license, even as an end-user. Either GPL or MIT would work. I don't plan to modify the code, but will send a PR if I find & fix any bugs.

**Comment by zwegner** [comment]
Oh right, good point, I've been lucky to not have to deal with that personally. I'll go with GPL for now.

**Comment by zwegner** [comment]
Added GPLv3. Thanks!
